"""agregar_campos_prompt_imagen_y_video_a_mensaje

Revision ID: ad60eef18e9a
Revises: 4782d32e1eb1
Create Date: 2025-11-27 16:30:28.712957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad60eef18e9a'
down_revision: Union[str, Sequence[str], None] = '4782d32e1eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensaje', sa.Column('prompt_imagen', sa.String(), nullable=True))
    op.add_column('mensaje', sa.Column('prompt_video', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mensaje', 'prompt_video')
    op.drop_column('mensaje', 'prompt_imagen')
    # ### end Alembic commands ###
